version: '3'
services:
  app:
    container_name: todoapp
    image: todoapp
    build: ./
    ports:
      - "9300:9300"
    depends_on:
      - couchbase-db
    networks:
      - my-network
    environment:
      APP_COUCHBASE_CONNECTION: couchbase-db
      APP_COUCHBASE_USERNAME: admin
      APP_COUCHBASE_PASSWORD: password
      APP_COUCHBASE_BUCKET_USER: user
      APP_COUCHBASE_BUCKET_TODO: todo
  couchbase-db:
    container_name: couchbase-db
    restart: always
    build: ./couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    networks:
      - my-network
networks:
  my-network: